### ISSUE TITLE
Redirect users to gulp-typescript in the README

### ISSUE THREAD

**Issue by ghost** [kant2002/gulp-tsc#19]
It does say "up to 1.6.3" near the bottom but preferably you would just redirect folks doing new development to gulp-typescript at the top -- assuming continuing development for this module is terminating.

**Comment by kant2002** [comment]
That module in the support mode. I add functionality when it is appear in TypeScript and when somebody has an issue. See #8 for rationale.

Please close if you mean something different.
/cc: @Toadskin
