### ISSUE TITLE
Gulp-tsc runs in infinite loop

### ISSUE THREAD

**Issue by Elfayer** [kant2002/gulp-tsc#20]
I guess i did something wrong, but I don't understand why starting with : 

![image](https://cloud.githubusercontent.com/assets/15869149/15008255/48687bc8-11df-11e6-87bd-b395dedf2223.png)

I end up with : (I had to stop the script from running, otherwise it never stops adding files and folders)

![image](https://cloud.githubusercontent.com/assets/15869149/15008278/7452adb2-11df-11e6-819f-9274d4bff661.png)

While the file is correctly compiled...

Here is my script : 

```
var gulp = require('gulp');
var typescript = require('gulp-tsc');

gulp.task('compileTS', function() {
    gulp.src(['**/*.ts', '!node_modules/**'])
    .pipe(typescript({
        target: 'ES5'
    }))
    .pipe(gulp.dest('.'));
});

gulp.task('watch:ts', function() {
    gulp.watch(['**/*.ts', '!node_modules/**'], ['compileTS']);
});
```

I just ran the `gulp watch:ts` command.

**Comment by kant2002** [comment]
@Elfayer `gulp-tsc` create file to keep tree. since `watch` see new file in the tree created, it relaunch new task, before other is appearing. In order to prevent `gulp-tsc` from create new script each time it compile you could add property `keepTree: false` to you options.

```
var gulp = require('gulp');
var typescript = require('gulp-tsc');

gulp.task('compileTS', function() {
    gulp.src(['**/*.ts', '!node_modules/**'])
    .pipe(typescript({
        target: 'ES5',
        keepTree: false
    }))
    .pipe(gulp.dest('.'));
});

gulp.task('watch:ts', function() {
    gulp.watch(['**/*.ts', '!node_modules/**'], ['compileTS']);
});
```
