### ISSUE TITLE
Using tsconfig

### ISSUE THREAD

**Issue by lexon0011** [kant2002/gulp-tsc#21]
Is it possible to use an existing tsconfig to setup the gulp-tsc? Because with the gulp-tsc options I could not configure `moduleResolution` or the `exclude` section.

Thx

Regards

**Comment by kant2002** [comment]
@lexon0011  As of version 1.2.2 you could use `moduleResolution` option. Also you could use `project` option to specify  folder where located your tsconfig.json so that should work for you.

Please report if you have any issues.

**Comment by kant2002** [comment]
Close this issue as don't have any feedback. Please reopen if needed.

**Comment by twjacobsen** [comment]
Hi,

I just tried your suggestion, since I prefer to not maintain settings in 2 places, as I manually run tsc from time to time.

I get this error: 

```
[11:03:59] Compiling TypeScript files using tsc version 2.1.1
[11:04:00] [tsc] > error TS5042: Option 'project' cannot be mixed with source files on a command line.
[11:04:00] Failed to compile TypeScript: Error: tsc command has exited with code:1
```

So it seems that when using the `--project` option for tsc, source files should not be passed along.

Here's the full snip of my gulp task:

```
return gulp.src('src/**/*.ts')
      .pipe($.tsc({
        project: './tsconfig.json'
      }))
      .pipe(gulp.dest('.tmp'));
```
