### ISSUE TITLE
option project

### ISSUE THREAD

**Issue by beckend** [kant2002/gulp-tsc#24]
When using it, I get `[tsc] > error TS5042: Option 'project' cannot be mixed with source files on a command line.`.
If I don't pass anything to `gulp.src` gulp will error, if I do, tsc will error.

**Comment by jnorkus** [comment]
This is a showstopper for me as I don't see another way to use tsconfig.json. I'll stick to gulp-shell for now.

**Comment by kant2002** [comment]
@jnorkus I thought a bit about this issue and don't fully understand your usecase. Could you be more specific on your issue?

**Comment by sjordan1975** [comment]
Getting the same error

**Comment by kant2002** [comment]
Fixed in 1.3.1
