### ISSUE TITLE
Should push 'jsx' option value

### ISSUE THREAD

**Issue by grahammendick** [kant2002/gulp-tsc#26]
The value of `jsx` must be either 'react' or 'preserve' but gulp-tsc [ignores the value of the jsx option passed in](https://github.com/kant2002/gulp-tsc/blob/master/lib/compiler.js#L98) and throws an error. (The Readme is also wrong because it lists the jsx option twice)

I can work around it using `additionalTscParameters`.

**Comment by kant2002** [comment]
@grahammendick Released as v1.2.6

**Comment by grahammendick** [comment]
Thanks for the fix, it works a treat 😄
