### ISSUE TITLE
When passing only 'project', the build incorrectly assumes 'target' = ES3

### ISSUE THREAD

**Issue by timhurkmans** [kant2002/gulp-tsc#28]
```
typescript({
        project: "tsconfig.json",
}
```
Results in:
<pre>
--module commonjs --target <b>ES3</b> --project tsconfig.json
</pre>
Expected:
```
--project tsconfig.json
```

Workaround:
```
typescript({
        project: "tsconfig.json",
        target: "ES5",
}
```
Results in:
<pre>
--module commonjs --target <b>ES5</b> --project tsconfig.json
</pre>

It messes up my code as tsconfig.json can define another module and target, and I don't want to duplicate the options.

**Comment by kant2002** [comment]
@timhurkmans Fixed in 1.3.2

Please free to reopen if you have any concerns
